from datetime import datetime
from typing import Protocol

from susiturkki.domain.goal import SeasonGoal
from susiturkki.domain.models import Entry, Group, Participant, Person


class Clock(Protocol):
    """Nykyhetki, jotta aikarajoja voi testata ilman kelloa."""

    def now(self) -> datetime: ...


class SkiRepository(Protocol):
    """Vaihdettava tallennus. Kirjaus kuuluu henkilölle ja näkyy hänen jokaisessa ryhmässään."""

    def add_group(self, name: str) -> Group: ...

    def rename_group(self, group_id: int, name: str) -> Group: ...

    def delete_group(self, group_id: int) -> None: ...

    def list_groups(self) -> list[Group]: ...

    def get_group(self, group_id: int) -> Group | None: ...

    def count_participants(self, group_id: int) -> int: ...

    def count_entries(self, group_id: int) -> int: ...

    def add_participant(self, group_id: int, given_name: str, family_name: str, token: str) -> Participant: ...

    def add_membership(self, group_id: int, person_id: int) -> Participant: ...

    def list_persons(self) -> list[Person]: ...

    def get_person_by_token(self, token: str) -> Person | None: ...

    def list_memberships(self, person_id: int) -> list[Participant]: ...

    def rename_participant(self, participant_id: int, given_name: str, family_name: str) -> Participant: ...

    def set_birth_year(self, person_id: int, year: int | None) -> None: ...

    def get_goal(self, person_id: int, season: int) -> SeasonGoal | None: ...

    def save_goal(self, goal: SeasonGoal) -> None: ...

    def delete_participant(self, participant_id: int) -> None: ...

    def list_participants(self, group_id: int) -> list[Participant]: ...

    def get_participant(self, participant_id: int) -> Participant | None: ...

    def replace_token(self, participant_id: int, token: str) -> Participant: ...

    def add_entry(
        self,
        person_id: int,
        performed_at: datetime,
        distance_tenths: int,
        place: str | None,
        created_at: datetime,
        style: str,
        conditions: str,
    ) -> Entry: ...

    def update_entry(
        self,
        entry_id: int,
        performed_at: datetime,
        distance_tenths: int,
        place: str | None,
        style: str,
        conditions: str,
    ) -> Entry: ...

    def delete_entry(self, entry_id: int) -> None: ...

    def get_entry(self, entry_id: int) -> Entry | None: ...

    def list_entries_for_person(self, person_id: int) -> list[Entry]: ...

    def list_entries_for_group(self, group_id: int) -> list[Entry]: ...
