from datetime import datetime
from typing import Protocol

from susiturkki.domain.models import Entry, Group, Participant


class Clock(Protocol):
    """Nykyhetki, jotta aikarajoja voi testata ilman kelloa."""

    def now(self) -> datetime: ...


class SkiRepository(Protocol):
    """Vaihdettava tallennusrajapinta ryhmille, osallistujille ja kirjauksille."""

    def add_group(self, name: str) -> Group: ...

    def rename_group(self, group_id: int, name: str) -> Group: ...

    def delete_group(self, group_id: int) -> None: ...

    def list_groups(self) -> list[Group]: ...

    def get_group(self, group_id: int) -> Group | None: ...

    def count_participants(self, group_id: int) -> int: ...

    def count_entries(self, group_id: int) -> int: ...

    def add_participant(self, group_id: int, name: str, token: str) -> Participant: ...

    def rename_participant(self, participant_id: int, name: str) -> Participant: ...

    def delete_participant(self, participant_id: int) -> None: ...

    def list_participants(self, group_id: int) -> list[Participant]: ...

    def get_participant(self, participant_id: int) -> Participant | None: ...

    def get_participant_by_token(self, token: str) -> Participant | None: ...

    def replace_token(self, participant_id: int, token: str) -> Participant: ...

    def add_entry(
        self,
        participant_id: int,
        performed_at: datetime,
        distance_tenths: int,
        place: str | None,
        created_at: datetime,
    ) -> Entry: ...

    def update_entry(
        self,
        entry_id: int,
        performed_at: datetime,
        distance_tenths: int,
        place: str | None,
    ) -> Entry: ...

    def delete_entry(self, entry_id: int) -> None: ...

    def get_entry(self, entry_id: int) -> Entry | None: ...

    def list_entries_for_participant(self, participant_id: int) -> list[Entry]: ...

    def list_entries_for_group(self, group_id: int) -> list[Entry]: ...
